version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: examples/Server/Dockerfile
    ports:
      - "8080:8080"

  otel-collector:
    image: otel/opentelemetry-collector:0.89.0
    restart: always
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./containers/opentelemetry/otel-collector.yml:/etc/otel-collector.yml
    ports:
      - "4317:4317" # otlp grpc
    depends_on:
      - tempo

  # To eventually offload to Tempo...
  tempo:
    image: grafana/tempo:2.3.0
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./containers/tempo/tempo.yml:/etc/tempo.yml
    ports:
      - "3200"  # tempo
      - "4317"  # otlp grpc

  grafana:
    image: grafana/grafana:10.2.0-ubuntu
    volumes:
      - ./containers/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports: 
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    depends_on:
      - tempo
