name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore ./AspNetCore.SignalR.OpenTelemetry.slnx

      - name: Build AspNetCore.SignalR.OpenTelemetry.csproj
        run: dotnet build ./src/AspNetCore.SignalR.OpenTelemetry/AspNetCore.SignalR.OpenTelemetry.csproj --no-restore

      - name: Test AspNetCore.SignalR.OpenTelemetry.Tests.csproj
        run: dotnet test ./tests/AspNetCore.SignalR.OpenTelemetry.Tests/AspNetCore.SignalR.OpenTelemetry.Tests.csproj --no-restore
